userauth/apps/authentication/urls.py
from django.urls import path
from authentication.views import SignUpView, ProfileView, HomeView, EditUserProfileView
from django.contrib.auth.views import LoginView, LogoutView

app_name='authentication'

urlpatterns = [
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('accounts/profile/', EditUserProfileView.as_view(), name='profile'),
    path('home/', HomeView.as_view(), name='home')
]

userauth/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from .settings import base


urlpatterns = static(base.MEDIA_URL, document_root=base.MEDIA_ROOT)
urlpatterns += static(base.STATIC_URL, document_root=base.STATIC_ROOT)


urlpatterns += [
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('authentication.urls')),

]

userauth/apps/authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.conf import settings
from datetime import datetime, date, timedelta
# from rest_framework.authtoken.models import Token
from django.urls import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives

class BaseModel(models.Model):
    # Timestamps
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    class Meta:
        abstract=True

class UserManager(BaseUserManager):
    """ Well.. using BaseUserManager """
    def create_user(self, email, password):
        if not email:
            raise ValueError("Users must register an email")

        user = self.model(email=UserManager.normalize_email(email))
        user.set_password(password)
        user.save(using=self._db)
        
        return user

    def create_superuser(self, email, password):
        user = self.create_user(email, password )
        user.is_active = True
        user.is_staff = True
        user.is_superuser = True
        user.is_admin = True
        user.save(using=self._db)

        return user

""" User Account Model """
class User(AbstractBaseUser, PermissionsMixin, BaseModel):
    email = models.EmailField(max_length=255, unique=True, db_index=True)
    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    # first_name = models.CharField(max_length=140,null=True, blank=True)
    # last_name = models.CharField(max_length=140,null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.profile.full_name


    @property
    def username(self):
        return self.email

    @property
    def profile(self):
        return self.user_profile.all()[0]

    def get_services_count(self):
        return self.user_services.all().count()

class UserProfile(BaseModel):
    user = models.ForeignKey(User,related_name='user_profile', on_delete=models.CASCADE)

    first_name = models.CharField(max_length=140)
    last_name = models.CharField(max_length=140)
    mobile_number = models.CharField(max_length=140)
    address = models.TextField(null=True, blank=True)
    city = models.CharField(max_length=140,null=True, blank=True)
    state = models.CharField(max_length=140,null=True, blank=True)
    zip_code = models.CharField(max_length=140,null=True, blank=True)
    profile_pic = models.FileField(upload_to='profile/', null=True, blank=True)
    company_name = models.CharField("Company Name",max_length=500,null=True, blank=True)

    @property
    def full_name(self):
        return self.user.first_name and "%s %s"%(self.user.first_name, self.user.last_name) or self.user.email

    def __str__(self):
        return self.user.email

    # def get_absolute_url(self):

    #     return reverse('users:user-profile-update' ,kwargs={'pk':self.pk})

    # def wallet_balance(self):
    #     total_credited = sum([w.balance for w in self.user.wallets.filter(type='1')])
    #     total_debited = sum([w.balance for w in self.user.wallets.filter(type='2')])
    #     return total_credited - total_debited

    # def total_earn(self):
    #     return sum([w.balance for w in self.user.wallets.filter(type='2')])

# """Use when send email on create user and contact form submition"""
# def send_email( subject, text_content, html_content):
#     from_email='alert@plumdry.com'
#     to_email=['support@plumdry.com']
#     msg = EmailMultiAlternatives(subject, text_content, from_email,to_email)
#     msg.attach_alternative(html_content, "text/html")
#     msg.send()

# def send_user_created_email(user_obj):
#     subject = "New User Added in plumdry"
#     text_content = render_to_string('email/users/user_create.txt',{'user' : user_obj})
#     html_content = render_to_string('email/users/user_create.html',{'user' : user_obj})
#     send_email( subject, text_content, html_content)

@receiver(post_save, sender=User)
def my_handler(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.get_or_create(user=instance)
        # Token.objects.get_or_create(user=instance)
        # send_user_created_email(instance)

userauth/apps/authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from authentication.models import UserProfile

User = get_user_model()

class RegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile

        fields = ['first_name' ,'last_name' ,'mobile_number' , 'address', 'city' ,'state' , 'zip_code', 'profile_pic', 'company_name'
        ]

userauth/apps/authentication/views.py
from django.shortcuts import render, redirect, HttpResponse, HttpResponseRedirect, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.views.generic import ListView, UpdateView, DetailView, CreateView, FormView, TemplateView, RedirectView
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from authentication.forms import RegistrationForm, UserProfileForm
from django.urls import reverse
from authentication.models import UserProfile
from django.contrib.auth import get_user_model

User = get_user_model()

class SignUpView(FormView):
    form_class = RegistrationForm
    template_name = 'registration/signup.html'

    def form_valid(self, form):
        user = form.save(False)
        user.set_password(form.cleaned_data.get('password1'))
        user.is_active = True
        user.save()

        user = authenticate(username=user.username, password=form.data['password1'])
        login(self.request, user)
        return HttpResponseRedirect(reverse('authentication:home'))

# class LoginView(FormView):
#     form_class = AuthenticationForm
#     template_name = 'registration/login.html'

#     def form_valid(self, form):
#         username = form.cleaned_data.get('username')
#         password = form.cleaned_data.get('password')
#         user = authenticate(username=username, password=password)
#         login(self.request, user)
#         return redirect('home')

# class LogoutView(RedirectView):
#     """
#     Provides users the ability to logout
#     """
#     url = '/home/'

#     def get(self, request, *args, **kwargs):
#         logout(request)
#         return super(LogoutView, self).get(request, *args, **kwargs)

class ProfileView(LoginRequiredMixin, View):
    login_url = '/accounts/login/'

    def get(self, request):

        return render(request, 'registration/profile.html')


class EditUserProfileView(LoginRequiredMixin, UpdateView): #Note that we are using UpdateView and not FormView
    model = UserProfile
    form_class = UserProfileForm
    template_name = "registration/profile.html"

    def get_object(self, *args, **kwargs):

        user = get_object_or_404(User, pk=self.request.user.pk)

        # We can also get user object using self.request.user  but that doesnt work
        # for other models.

        return user.profile

    def get_success_url(self, *args, **kwargs):
        return reverse("authentication:profile")


class HomeView(TemplateView):
    template_name = 'deshboard.html'

userauth/templates/base.html
{% load i18n staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="icon" href="{% static 'img/favicon.png' %}">

        <title>{% trans 'LOGIN' %}</title>

        <meta name="author" content="" />
        <meta name="description" content="" />
        <link rel='canonical' href=''/>

        {% block stylesheet %}
            <!-- Google font -->
            <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

            <!-- Bootstrap -->
            <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>

            <link type="text/css" rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>

            <link type="text/css" rel="stylesheet" href="{% static 'css/custom.css' %}"/>

        {% endblock %}

    </head>

    <body class="top-navigation">
        <div id="wrapper">
            <div id="page-wrapper" class="gray-bg">
                {% block header %}{% endblock %}
                {% block content %}{% endblock %}
                {% block footer %}{% endblock %}
            </div>
        </div>
    </body>
    
    {% block script %}
        <!-- jQuery Plugins -->
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>

        <!-- custom js-->

        {% block js%} {% endblock %}
    {% endblock %}
</html>

userauth/templates/deshboard.html
{% extends 'layout.html' %}
{% load i18n staticfiles widget_tweaks%}

{% block title %}Home{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <h4><a href="{% url 'authentication:login' %}">LogOut</a></h4>
        Hi {{ user.username }}!
        <h4><a href="{% url 'authentication:profile' %}">Profile</a></h4>
    {% else %}
        <p>You are not logged in</p>
        <a href="{% url 'authentication:login' %}">login</a>
    {% endif %}
{% endblock %}

userauth/templates/footer.html
{% load i18n staticfiles %}

userauth/templates/header.html
{% load i18n staticfiles %}

userauth/templates/layout.html
{% extends 'base.html' %}
{% load i18n staticfiles %}

{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}